language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - DJANGO=1.4.14
  - DJANGO=1.5.9
  - DJANGO=1.6.8
  - DJANGO=1.7.1

matrix:
  allow_failures:
    # Allow failures for legacy django versions
    - env: DJANGO=1.4.14
    - env: DJANGO=1.5.9
  exclude:
    - env: DJANGO=1.4.14
      python: "3.3"
    - env: DJANGO=1.7.1
      python: "2.6"
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors
script:
  - python setup.py test
